pipeline {
  agent any
  stages {
    stage('Workspace Cleanup') {
      steps {
        // Clean before build
        cleanWs()
        echo 'Cleaning workspace...'
      }
    }
    stage('Checkout Git Branch') {
      steps {
        checkout scmGit(branches: [[name: '*/main']], extensions: [], userRemoteConfigs: [[credentialsId: 'github-credentials', url: 'https://github.com/RutujaBangera/To-Do-list.git']])
      }
    }
   stage('Build Appliaction') {
    steps {
        git branch: 'main', credentialsId: 'github-credentials', url: 'https://github.com/RutujaBangera/To-Do-list.git'
        bat 'python -m pip install --upgrade pip'
        bat 'pip install -r C:\ProgramData\Jenkins\.jenkins\workspace\Python_TodoList\todo_app'
        bat 'python main.py'
    }
   }
   stage('Test') {
    steps {
        echo "The job has been tested"
    }
   }
  }
}
