pipeline {
  agent any
  stages {
    stage('Workspace Cleanup') {
      steps {
        // Clean before build
        cleanWs()
        echo 'Cleaning workspace...'
      }
    }
    stage('Checkout Git Branch') {
      steps {
        git branch: 'main', credentialsId: 'github-credentials', url: 'https://github.com/RutujaBangera/To-Do-list.git'
      }
    }
    stage('Build Application') {
      steps {
        bat 'py -m pip install --upgrade pip'
        bat 'pip install -r requirements.txt'
      }
    }
  }
}
